import { createFileRoute, Link } from "@tanstack/react-router";
import { BridgeIcon } from "@/components/BridgeIcon";

function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8">
          <Link to="/" className="flex items-center gap-2 text-primary transition hover:opacity-80">
            <BridgeIcon className="h-7 w-7" />
            <span className="font-serif text-2xl">CVLingo</span>
          </Link>
          <Link to="/" className="text-sm font-medium text-muted-foreground transition hover:text-foreground">
            ← Back to home
          </Link>
        </div>
      </header>
      <section className="mx-auto max-w-3xl px-4 py-10 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-semibold sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: June 2026</p>
        <div className="prose mt-6 max-w-none space-y-6 text-foreground">
          <p>
            By using CVLingo you agree to these terms.
          </p>

          <h2 className="text-xl font-semibold">Use of the Platform</h2>
          <p>
            CVLingo is free for job seekers. You must provide accurate information when building your CV. You are responsible for the content of your CV.
          </p>

          <h2 className="text-xl font-semibold">Intellectual Property</h2>
          <p>
            CVs generated by CVLingo are yours to use. The CVLingo name, logo, and platform design are owned by Jebaco Global.
          </p>

          <h2 className="text-xl font-semibold">Limitations</h2>
          <p>
            CVLingo provides CV generation as a tool. We do not guarantee employment outcomes. We are not a recruitment agency.
          </p>

          <h2 className="text-xl font-semibold">Acceptable Use</h2>
          <p>
            You must not use CVLingo to create false or misleading CVs, or to misrepresent your identity or qualifications.
          </p>

          <h2 className="text-xl font-semibold">Changes to Service</h2>
          <p>
            We reserve the right to update or discontinue features at any time.
          </p>

          <h2 className="text-xl font-semibold">Contact</h2>
          <p>
            For any queries email{" "}
            <a href="mailto:hello@cvlingo.com" className="text-primary underline">hello@cvlingo.com</a>
          </p>
        </div>
      </section>
    </main>
  );
}

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: "Terms of Service — CVLingo" },
      { name: "description", content: "Terms and conditions for using CVLingo. Free CV builder for UK job seekers." },
    ],
    links: [{ rel: "canonical", href: "https://cvlingo.com/terms" }],
  }),
});
