/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RefCodeRouteImport } from './routes/ref.$code'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminJobRequestsRouteImport } from './routes/admin.job-requests'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobRequestsRoute = AdminJobRequestsRouteImport.update({
  id: '/job-requests',
  path: '/job-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/job-requests': typeof AdminJobRequestsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/team': typeof AdminTeamRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/job-requests': typeof AdminJobRequestsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/team': typeof AdminTeamRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/job-requests': typeof AdminJobRequestsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/team': typeof AdminTeamRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/job-requests'
    | '/admin/partners'
    | '/admin/team'
    | '/partner/dashboard'
    | '/ref/$code'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/job-requests'
    | '/admin/partners'
    | '/admin/team'
    | '/partner/dashboard'
    | '/ref/$code'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/billing'
    | '/admin/candidates'
    | '/admin/job-requests'
    | '/admin/partners'
    | '/admin/team'
    | '/partner/dashboard'
    | '/ref/$code'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuildRoute: typeof BuildRoute
  CandidatesRoute: typeof CandidatesRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRoute: typeof EmployerRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultRoute: typeof ResultRoute
  TermsRoute: typeof TermsRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  RefCodeRoute: typeof RefCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/job-requests': {
      id: '/admin/job-requests'
      path: '/job-requests'
      fullPath: '/admin/job-requests'
      preLoaderRoute: typeof AdminJobRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminJobRequestsRoute: typeof AdminJobRequestsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminJobRequestsRoute: AdminJobRequestsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuildRoute: BuildRoute,
  CandidatesRoute: CandidatesRoute,
  DashboardRoute: DashboardRoute,
  EmployerRoute: EmployerRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResultRoute: ResultRoute,
  TermsRoute: TermsRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  RefCodeRoute: RefCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
