/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResultRouteImport } from './routes/result'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as RefCodeRouteImport } from './routes/ref.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/build': typeof BuildRoute
  '/candidates': typeof CandidatesRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/candidates'
    | '/admin/partners'
    | '/ref/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/candidates'
    | '/admin/partners'
    | '/ref/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/build'
    | '/candidates'
    | '/dashboard'
    | '/employer'
    | '/partners'
    | '/privacy'
    | '/result'
    | '/terms'
    | '/admin/candidates'
    | '/admin/partners'
    | '/ref/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuildRoute: typeof BuildRoute
  CandidatesRoute: typeof CandidatesRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRoute: typeof EmployerRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultRoute: typeof ResultRoute
  TermsRoute: typeof TermsRoute
  RefCodeRoute: typeof RefCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuildRoute: BuildRoute,
  CandidatesRoute: CandidatesRoute,
  DashboardRoute: DashboardRoute,
  EmployerRoute: EmployerRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResultRoute: ResultRoute,
  TermsRoute: TermsRoute,
  RefCodeRoute: RefCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
