/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as BuildRouteImport } from './routes/build'
import { Route as IndexRouteImport } from './routes/index'

const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/build.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/employer': typeof EmployerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/employer': typeof EmployerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/employer': typeof EmployerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build' | '/employer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build' | '/employer'
  id: '__root__' | '/' | '/build' | '/employer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  EmployerRoute: typeof EmployerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  EmployerRoute: EmployerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
